#!/bin/bash

for file in ~/.{bash_exports,bash_work,bash_aliases,bash_completion,functions}; do
    [ -r "$file" ] && source "$file"
done
unset file

# Load liquidprompt
[ -f $DOTFILES/liquidprompt ] && source $DOTFILES/liquidprompt

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
